# Pipeline
name: hello-word # Nom du workflow
on: [push]
jobs:
  # Premier hello word
  hello-word:
    # Définition du runner (ubuntu:latest)
    runs-on: ubuntu-latest
    # Déclaration de la liste des steps
    steps:     
      - uses: actions/checkout@v3
      - name: hello word
       # Run permet d'executer une commande bash
        run: echo "hello word"
   