name: push  and pull
on: [push, pull_request]
env: 
  NAME: push
  NAME2:  pull_request


jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: pull
        if: ${{ github.event_name == 'push' }}
        run: echo "c est un pull."
  
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: pull_request
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "c est un pull resquest"