name: push  and pull
on: [push, pull_request]
env: 
  NAME: 
    push
    pull_request


jobs:
  if-pull:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: condition 1
      if: ${{ github.event_name == 'push' }}
      run: echo "c est un pull."
    - name: condition 2
      if: ${{ github.event_name == 'pull_request' }}
      run: echo "c est un pull resquest"