name: push  and pull
on: [push, pull_request]
env: 
  NAME: push and pull requests


jobs:
  if-pull:
    runs-on: ubuntu-latest
    steps:
      - name: condition 1
        if: runner.os == 'pull'
        run: echo "c est un pull."
      - name: condition 2
        if: runner.os = 'pull_resquest'
        run: echo "c est un pull resquest."
  