name: push  and pull
on: [push, pull_request]
env: 
  NAME:  c'est un push
  NAME2:  c'est pull_request


jobs:
  push:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: push
        run: echo "$NAME"
  
  pull_request:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: pull_request
        run: echo "$NAME2"