name: Hello Mahamadou
on: workflow_dispatch
env: 
  NAME: Mahamadou

jobs:
  dit_bonjour:
    runs-on : ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Dit bonjour"
        if: ${{env.NAME !='Mahamadou'}}
        run: echo "Coucou "$NAME! tu  n'est pas $NAME ?!"
      - name: "coucou Mahamadou"
        if: ${{env.NAME =='Mahamadou'}}
        run : echo " salut $NAME, tu alaire en pleine forme"
