name: Upload Artifact

on: workflow_dispatch

jobs:
    upload:
      name: upload
      runs-on: ubuntu-latest
      steps:
        - name: lire le fichier
          run: "coucou toi artifact"
        - name: Upload Artifact
          uses: actions/upload-artifact@v3
          with:
            name: Artifact
            path: artifact.txt
    
    
    download:

      name: download
      needs: upload
      runs-on: ubuntu-latest
      steps:
        - name: download
          run: "coucou toi dowbload artifact"
        - name: Upload Artifact
          uses: actions/download-artifact@v3
          with:
            name: Artifact
            path: cat artifact.txt
